#define MONETA_REQUIRE_HEIGHT_TEST 0
#define MONETA_REQUIRE_HEIGHT 0

#define MONETA_PCH_MESSAGE_START_TEST_0 0xfd
#define MONETA_PCH_MESSAGE_START_TEST_1 0xd2
#define MONETA_PCH_MESSAGE_START_TEST_2 0xc8
#define MONETA_PCH_MESSAGE_START_TEST_3 0xf1

#define MONETA_PCH_MESSAGE_START_0 0xfb
#define MONETA_PCH_MESSAGE_START_1 0xc0
#define MONETA_PCH_MESSAGE_START_2 0xb6
#define MONETA_PCH_MESSAGE_START_3 0xdb

#define MONETA_MAINNET_SEED_0 "host0"
#define MONETA_MAINNET_SEED_1 "host1"
#define MONETA_MAINNET_SEED_2 "host2"
#define MONETA_MAINNET_SEED_3 "host3"

#define MONETA_TESTNET_SEED_0 "172.18.0.10"

#define MONETA_PROTOCOL_VERSION 70015
